import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import ReactQueryProvider from "@/lib/providers/queryClient";
import "../globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Blog Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable}  antialiased`}>
        <Navbar />
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Footer />
      </body>
    </html>
  );
}
